remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: OpenGRC Documentation
description: OpenGRC is a free and open-source Governance Risk and Compliance tool
show_downloads: true
